
pastEvents: [
    {
    	date: new Date(2023, 1, 26, 18),
    	img: require('~/assets/event-images/zielsgelukkig.svg'),
    	name: 'Zielsgelukkig Spirituele beurs',
    	text_1: '11.00 - 17.00 Deurne.',
    	text_2: 'Kloosterhotel Willibrordhaeghe (Vlierdenseweg 109)',
    	href: 'https://zielsgelukkigverbinding.nl/',
    },
    {
    	date: new Date(2023, 2, 19, 18),
    	img: require('~/assets/event-images/einder.svg'),
    	name: 'Spirituele beurs Lightning',
    	text_1: '10.30 - 17.00 Someren-Eind.',
    	text_2: 'M.F. Centrum De Einder (Einderplein 1)',
    	href: 'https://www.facebook.com/events/703587454908443/',
    },
    {
    	date: new Date(2023, 2, 26, 18),
    	img: require('~/assets/event-images/buitenlust.svg'),
    	name: 'Maandelijkse mediumdagen (elke laatste zondag vd maand)',
    	text_1: '10.00 - 17.00 Vught.',
    	text_2: 'Koffie en Theetuin Buitenlust (Esscheweg 274A)',
    	href: 'https://www.buitenlustvught.nl/mediumdagen/',
    },
    {
    	date: new Date(2023, 3, 2, 18),
    	img: require('~/assets/event-images/souls_logo.svg'),
    	name: 'Spirituele beurs Souls',
    	text_1: '10.00 - 17.00 Nijnsel.',
    	text_2: 'De Beckart (Oude Lieshoutseweg 7)',
    	href: 'https://www.facebook.com/events/694063912411987',
    },
    {
    	date: new Date(2023, 3, 30, 18),
    	img: require('~/assets/event-images/buitenlust.svg'),
    	name: 'Maandelijkse mediumdagen (elke laatste zondag vd maand)',
    	text_1: '10.00 - 17.00 Vught.',
    	text_2: 'Koffie en Theetuin Buitenlust (Esscheweg 274A)',
    	href: 'https://www.buitenlustvught.nl/mediumdagen/',
    },
    {
    	date: new Date(2023, 4, 28, 18),
    	img: require('~/assets/event-images/buitenlust.svg'),
    	name: 'Maandelijkse mediumdagen (elke laatste zondag vd maand)',
    	text_1: '10.00 - 17.00 Vught.',
    	text_2: 'Koffie en Theetuin Buitenlust (Esscheweg 274A)',
    	href: 'https://www.buitenlustvught.nl/mediumdagen/',
    },
    {
    	date: new Date(2023, 4, 21, 18),
    	img: require('~/assets/event-images/zielsgelukkig.svg'),
    	name: 'Zielsgelukkig Spirituele beurs',
    	text_1: '10.00 - 16.00 Berg en Dal.',
    	text_2: 'Fletcher Hotel-Restaurant Erica (Molenbosweg 17)',
    	href: 'https://www.facebook.com/events/6246930658650927',
    },
    {
    	date: new Date(2023, 5, 11, 18),
    	img: require('~/assets/event-images/einder.svg'),
    	name: 'Spirituele beurs Lightning',
    	text_1: '10.30 - 17.00 Someren-Eind.',
    	text_2: 'M.F. Centrum De Einder (Einderplein 1)',
    	href: '',
    },
    {
    	date: new Date(2023, 5, 24, 18),
    	img: require('~/assets/event-images/natuurhuisje.svg'),
    	name: 'Leefstijl Feest',
    	text_1: '11.00 - 16.00 Nederasselt.',
    	text_2: 'Natuurhuisje (Sluisweg 1)',
    	href: 'https://www.facebook.com/profile.php?id=100077136530443',
    },
    {
    	date: new Date(2023, 5, 25, 18),
    	img: require('~/assets/event-images/buitenlust.svg'),
    	name: 'Maandelijkse mediumdagen (elke laatste zondag vd maand)',
    	text_1: '10.00 - 17.00 Vught.',
    	text_2: 'Koffie en Theetuin Buitenlust (Esscheweg 274A)',
    	href: 'https://www.buitenlustvught.nl/mediumdagen/',
    },
    {
    	date: new Date(2023, 6, 2, 18),
    	img: require('~/assets/event-images/zielsgelukkig.svg'),
    	name: 'Zielsgelukkig Spirituele beurs',
    	text_1: '10.00 - 16.00 Noordwijk.',
    	text_2: 'Fletcher Hotel-Restaurant De Witte Raaf (Duinweg 117)',
    	href: 'https://www.facebook.com/events/s/zielsgelukkig-festival/599935065332942/',
    },
    {
    	date: new Date(2023, 6, 30, 18),
    	img: require('~/assets/event-images/buitenlust.svg'),
    	name: 'Maandelijkse mediumdagen (elke laatste zondag vd maand)',
    	text_1: '10.00 - 17.00 Vught.',
    	text_2: 'Koffie en Theetuin Buitenlust (Esscheweg 274A)',
    	href: 'https://www.buitenlustvught.nl/mediumdagen/',
    },
    {
    	date: new Date(2023, 7, 26, 18),
    	img: require('~/assets/event-images/bibliotheekoostland.svg'),
    	name: 'Paranormale Beurs',
    	text_1: '10.00 - 17.00 Bergschenhoek.',
    	text_2: 'Bibliotheek Oostland (Wilhelminastraat 1A)',
    	href: 'https://www.facebook.com/events/3691329454526363',
    },
    {
    	date: new Date(2023, 7, 27, 18),
    	img: require('~/assets/event-images/buitenlust.svg'),
    	name: 'Maandelijkse mediumdagen (elke laatste zondag vd maand)',
    	text_1: '10.00 - 17.00 Vught.',
    	text_2: 'Koffie en Theetuin Buitenlust (Esscheweg 274A)',
    	href: 'https://www.buitenlustvught.nl/mediumdagen/',
    },
    {
    	date: new Date(2023, 8, 24, 18),
    	img: require('~/assets/event-images/buitenlust.svg'),
    	name: 'Maandelijkse mediumdagen (elke laatste zondag vd maand)',
    	text_1: '10.00 - 17.00 Vught.',
    	text_2: 'Koffie en Theetuin Buitenlust (Esscheweg 274A)',
    	href: 'https://www.buitenlustvught.nl/mediumdagen/',
    },
    {
    	date: new Date(2023, 9, 8, 18),
    	text_logo: 'De Donderie',
    	name: 'Roermond Spiritueel',
    	text_1: '10.00 - 17.00 Roermond.',
    	text_2: 'De Donderie (Donderbergweg 47)',
    	href: 'https://www.facebook.com/profile.php?id=61551055863898',
    },
    {
    	date: new Date(2023, 9, 15, 18),
    	img: require('~/assets/event-images/souls_logo.svg'),
    	name: 'Spirituele beurs Souls',
    	text_1: '10.00 - 17.00 Nijnsel.',
    	text_2: 'De Beckart (Oude Lieshoutseweg 7)',
    	href: 'https://www.facebook.com/events/752166309720601?acontext=%7B%22event_action_history%22%3A[]%7D',
    },
    {
    	date: new Date(2023, 9, 28, 18),
    	name: 'Million Dreams Festival of Love, Freedom & Health',
    	text_logo: 'Dorpshuis Zeddam',
    	text_1: '11.00 - 17.00 Zeddam.',
    	text_2: 'Het Dorpshuis (Gerrit Varwijckplein 25)',
    	href: 'https://www.facebook.com/groups/571813376237192/permalink/6559883924096744/?sfnsn=mo&ref=share',
    },
    {
    	date: new Date(2023, 9, 29, 18),
    	img: require('~/assets/event-images/buitenlust.svg'),
    	name: 'Maandelijkse mediumdagen (elke laatste zondag vd maand)',
    	text_1: '10.00 - 17.00 Vught.',
    	text_2: 'Koffie en Theetuin Buitenlust (Esscheweg 274A)',
    	href: 'https://www.buitenlustvught.nl/mediumdagen/',
    },
    {
    	date: new Date(2023, 10, 5, 18),
    	img: require('~/assets/event-images/likrali.svg'),
    	name: 'LiKraLi',
    	text_1: '11.00 - 17.00 Venray.',
    	text_2: 'De Witte Hoeve (Gasstraat 5)',
    	href: 'https://www.facebook.com/groups/368354643682751/permalink/1593958921122311/',
    },
    {
    	date: new Date(2023, 10, 12, 18),
    	text_logo: 'Lievendaal',
    	name: 'Heavenly Heart Spirituele beurs',
    	text_1: '11.00 - 17.00 Eindhoven.',
    	text_2: 'Gemeenschapscentrum Lievendaal (Lievendaalseweg 3)',
    	href: 'https://www.facebook.com/groups/571813376237192/permalink/6505747856177018/?sfnsn=mo&ref=share',
    },
    {
    	date: new Date(2023, 10, 26, 18),
    	img: require('~/assets/event-images/einder.svg'),
    	name: 'Spirituele beurs Lightning',
    	text_1: '10.30 - 17.00 Someren-Eind.',
    	text_2: 'M.F. Centrum De Einder (Einderplein 1)',
    	href: 'https://gemeenschapshuis-de-einder.nl/',
    },
    {
    	date: new Date(2023, 11, 10, 18),
    	text_logo: 'Princeville',
    	name: 'Grote Spirituele Beurs',
    	text_1: '11.00 - 17.00 Breda.',
    	text_2: 'Hotel Princeville (Princenhagelaan 5)',
    	href: 'https://www.vandervalkbreda.com/',
    },
    {
    	date: new Date(2023, 11, 30, 18),
    	img: require('~/assets/event-images/bibliotheekoostland.svg'),
    	name: 'Spirituele Winter Wonderland',
    	text_1: '10.00 - 17.00 Bergschenhoek.',
    	text_2: 'Bibliotheek Oostland (Wilhelminastraat 1A)',
    	href: 'https://www.facebook.com/groups/571813376237192/permalink/6933955503356249/',
    },
    {
    	date: this.newDate(31, 3, 2024),
    	img: require('~/assets/event-images/buitenlust.svg'),
    	name: 'Maandelijkse mediumdagen (elke laatste zondag vd maand)',
    	text_1: '10.00 - 17.00 Vught.',
    	text_2: 'Koffie en Theetuin Buitenlust (Esscheweg 274A)',
    	href: 'https://www.buitenlustvught.nl/mediumdagen/',
    },
    {
    	date: this.newDate(17, 3, 2024),
    	img: require('~/assets/event-images/heavenly-heart.svg'),
    	name: 'Heavenly Heart',
    	text_1: '11.00 - 17.00 Eindhoven.',
    	text_2: 'Lievendaal (Lievendaalseweg 3)',
    	href: 'https://www.heavenlyheart.nl/',
    },
    {
    	date: this.newDate(1, 4, 2024),
    	img: require('~/assets/event-images/bogerd.svg'),
    	name: 'Bewust, Gezond & Alternatief Beurs',
    	text_1: '11.00 - 16.00 Druten.',
    	text_2: 'De Bogerd (Van Heemstraweg 53)',
    	href: 'https://www.facebook.com/photo/?fbid=6206063586166638&set=a.458472610925793', // https://bogerddruten.nl/
    },
	{
    	date: this.newDate(14, 4, 2024),
    	img: require('~/assets/event-images/souls_logo.svg'),
    	name: 'Spirituele beurs Souls',
    	text_1: '10.00 - 17.00 Nijnsel.',
    	text_2: 'De Beckart (Oude Lieshoutseweg 7)',
    	href: 'https://www.facebook.com/events/3700776286873436',
    },
    {
    	date: this.newDate(7, 4, 2024),
    	text_logo: 'Stichting Horus',
    	name: 'Paranormale Beurs Horus',
    	text_1: '11.00 - 17.00 Berlicum.',
    	text_2: 'Den Durpsherd (Kerkswijk 61)',
    	href: 'https://www.facebook.com/stichtinghorus',
    },
    {
    	date: this.newDate(28, 4, 2024),
    	img: require('~/assets/event-images/buitenlust.svg'),
    	name: 'Maandelijkse mediumdagen (elke laatste zondag vd maand)',
    	text_1: '10.00 - 17.00 Vught.',
    	text_2: 'Koffie en Theetuin Buitenlust (Esscheweg 274A)',
    	href: 'https://www.buitenlustvught.nl/mediumdagen/',
    },
    {
    	date: this.newDate(26, 5, 2024),
    	img: require('~/assets/event-images/buitenlust.svg'),
    	name: 'Maandelijkse mediumdagen (elke laatste zondag vd maand)',
    	text_1: '10.00 - 17.00 Vught.',
    	text_2: 'Koffie en Theetuin Buitenlust (Esscheweg 274A)',
    	href: 'https://www.buitenlustvught.nl/mediumdagen/',
    },
    {
    	from_date: 1,
    	date: this.newDate(2, 6, 2024),
    	img: require('~/assets/event-images/bendefestijn.svg'),
    	name: 'Bendefestijn',
    	text_1: '11.00 - 22.00 Nieuwkuijk.',
    	text_2: 'Abdij Mariënkroon (Abdijlaan 12)',
    	href: 'https://www.facebook.com/events/324064563520480/?acontext=%7B%22event_action_history%22%3A[]%7D',
    },
    {
    	date: this.newDate(2, 6, 2024),
    	img: require('~/assets/event-images/ulingsheide.svg'),
    	name: 'Spirituele Gezondheidsbeurs',
    	text_1: '10.00 - 18.00 Tegelen.', // Moet nog!!!
    	text_2: 'Abdij Ulingsheide (Ulingsheide 3)',
    	href: 'https://www.facebook.com/events/324064563520480/?acontext=%7B%22event_action_history%22%3A[]%7D',
    },
    {
    	date: this.newDate(23, 6, 2024),
    	img: require('~/assets/event-images/heavenly-heart.svg'),
    	name: 'Heavenly Heart',
    	text_1: '11.00 - 17.00 Eindhoven.',
    	text_2: 'Lievendaal (Lievendaalseweg 3)',
    	href: 'https://www.heavenlyheart.nl/',
    },
    {
    	from_date: 27,
    	date: this.newDate(30, 6, 2024),
    	text_logo: 'Chapat',
    	name: 'Chapat Sjamanistisch Festival',
    	text_1: '10.00 - 17.00 Reusel.',
    	text_2: 'Terrein de Wilgenspot (Langemiersedijk)',
    	href: 'https://www.facebook.com/ChapatSjamanistischFestival',
    },
    {
    	date: this.newDate(28, 7, 2024),
    	img: require('~/assets/event-images/buitenlust.svg'),
    	name: 'Maandelijkse mediumdagen (elke laatste zondag vd maand)',
    	text_1: '10.00 - 17.00 Vught.',
    	text_2: 'Koffie en Theetuin Buitenlust (Esscheweg 274A)',
    	href: 'https://www.buitenlustvught.nl/mediumdagen/',
    },
    {
    	date: this.newDate(4, 8, 2024),
    	img: require('~/assets/event-images/zielsgelukkig.svg'),
    	name: 'Zielsgelukkig Festival',
    	text_1: '11.00 - 17.00 Baarlo.',
    	text_2: 'Fletcher Hotel Château De Raay (Raayerveldlaan 6)',
    	href: 'https://zielsgelukkigverbinding.nl/',
    },
    {
    	date: this.newDate(1, 9, 2024),
    	img: require('~/assets/event-images/zielsgelukkig.svg'),
    	name: 'Zielsgelukkig Festival',
    	text_1: '11.00 - 17.00 Nijmegen.',
    	text_2: 'Museumpark Orientalis (Profetenlaan 2)',
    	href: 'https://zielsgelukkigverbinding.nl/',
    },
    {
    	date: this.newDate(25, 8, 2024),
    	img: require('~/assets/event-images/buitenlust.svg'),
    	name: 'Maandelijkse mediumdagen (elke laatste zondag vd maand)',
    	text_1: '10.00 - 17.00 Vught.',
    	text_2: 'Koffie en Theetuin Buitenlust (Esscheweg 274A)',
    	href: 'https://www.buitenlustvught.nl/mediumdagen/',
    },
    {
    	date: this.newDate(29, 9, 2024),
    	img: require('~/assets/event-images/buitenlust.svg'),
    	name: 'Maandelijkse mediumdagen (elke laatste zondag vd maand)',
    	text_1: '10.00 - 17.00 Vught.',
    	text_2: 'Koffie en Theetuin Buitenlust (Esscheweg 274A)',
    	href: 'https://www.buitenlustvught.nl/mediumdagen/',
    },
    {
    	date: this.newDate(20, 10, 2024),
    	img: require('~/assets/event-images/souls_logo.svg'),
    	name: 'Spirituele beurs Souls',
    	text_1: '10.00 - 17.00 Nijnsel.',
    	text_2: 'De Beckart (Oude Lieshoutseweg 7)',
    	href: 'https://www.facebook.com/soulsspirituelebeurs',
    },
    {
    	date: this.newDate(27, 10, 2024),
    	img: require('~/assets/event-images/buitenlust.svg'),
    	name: 'Maandelijkse mediumdagen (elke laatste zondag vd maand)',
    	text_1: '10.00 - 17.00 Vught.',
    	text_2: 'Koffie en Theetuin Buitenlust (Esscheweg 274A)',
    	href: 'https://www.buitenlustvught.nl/mediumdagen/',
    },
	{
		date: this.newDate(16, 3, 2025),
		img: this.requireImg('horus'),
		name: 'Paranormale Beurs Horus',
		text_1: '11.00 - 17.00 Berlicum.',
		text_2: 'Den Durpsherd (Kerkswijk 61)',
		href: 'https://www.facebook.com/stichtinghorus',
	},
	{
		date: this.newDate(30, 3, 2025),
		img: require('~/assets/event-images/buitenlust.svg'),
		name: 'Maandelijkse mediumdagen (elke laatste zondag vd maand)',
		text_1: '10.00 - 17.00 Vught.',
		text_2: 'Koffie en Theetuin Buitenlust (Esscheweg 274A)',
		href: 'https://www.buitenlustvught.nl/mediumdagen/',
	},
	{
		date: this.newDate(6, 4, 2025),
		img: this.requireImg('haammaeker'),
		name: 'Spirituele Beurs',
		text_1: '11.00 - 17.00 Neer.',
		text_2: 'Gemeensschapshuis D’n Haammaeker (Hoogstraat 2)',
		href: 'https://haammaeker.nl/save-the-date-spirituele-beurs/',
	},
	{
		date: this.newDate(13, 4, 2025),
		img: this.requireImg('souls_logo'),
		name: 'Spirituele beurs Souls',
		text_1: '10.00 - 17.00 Nijnsel.',
		text_2: 'De Beckart (Oude Lieshoutseweg 7)',
		href: 'https://www.facebook.com/soulsspirituelebeurs',
	},
	{
		date: this.newDate(21, 4, 2025),
		img: require('~/assets/event-images/bogerd.svg'),
		name: 'Bewust, Gezond & Alternatief Beurs',
		text_1: '11.00 - 17.00 Druten.',
		text_2: 'De Bogerd (Van Heemstraweg 53)',
		href: 'https://www.facebook.com/events/544328485072431/', // https://bogerddruten.nl/
	},
	{
		date: this.newDate(27, 4, 2025),
		img: require('~/assets/event-images/buitenlust.svg'),
		name: 'Maandelijkse mediumdagen (elke laatste zondag vd maand)',
		text_1: '10.00 - 17.00 Vught.',
		text_2: 'Koffie en Theetuin Buitenlust (Esscheweg 274A)',
		href: 'https://www.buitenlustvught.nl/mediumdagen/',
	},
]